basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for delivering cryptocurrencies
  version: "1.0"
paths:
  /currencies:
    get:
      consumes:
      - application/json
      description: Get maximum rates for a list of currencies
      parameters:
      - description: Comma-separated list of currency symbols (e.g., BTC,ETH)
        in: query
        name: currencies
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get maximum rates for currencies
      tags:
      - rates
  /rates:
    get:
      consumes:
      - application/json
      description: Get minimum rates for a list of currencies
      parameters:
      - description: Comma-separated list of currency symbols (e.g., BTC,ETH)
        in: query
        name: currencies
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get minimum rates for currencies
      tags:
      - rates
  /rates/{currency}/latest:
    get:
      consumes:
      - application/json
      description: Get the average rate for a specific currency
      parameters:
      - description: Currency symbol (e.g., BTC)
        in: path
        name: currency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get average rate for a currency
      tags:
      - rates
  /rates/{currency}/max:
    get:
      consumes:
      - application/json
      description: Get the last recorded rate for a specific currency
      parameters:
      - description: Currency symbol (e.g., BTC)
        in: path
        name: currency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get last rate for a currency
      tags:
      - rates
swagger: "2.0"
